---

# virtual_env_name: eventup

# Gale VanRossem playbook for EVENTup dev environment
- hosts: localhost
  connection: local
  tasks:
    - homebrew: name=python state=present
    - homebrew: name=python3 state=present
    - pip: name=virtualenvwrapper
    - command: mkvirtualenv eventup

